### ISSUE TITLE
Unit tests are extremely slow 

### ISSUE THREAD

**Issue by melezhik** [grondilu/pbkdf2-raku#2]
Please see this report - https://ci.sparrowhub.io/report/2088, it shows 13 minutes 45 sec, which is really weird ... I tested against rakudo binary 2022.12 downloaded from rakudo.org

**Comment by grondilu** [comment]
They are indeed.

I suppose I could go back to using the openssl call for hmac-sha1 instead of the pure raku implemetation.

**Comment by melezhik** [comment]
Ok, then this is not an issue ... Or at least something you are aware of ...

**Comment by grondilu** [comment]
For testing, version 0.3.0 uses `Digest::SHA1::Native` instead of `Digest::SHA1`.  That should speed things up quite a bit.

**Comment by melezhik** [comment]
let me check

**Comment by melezhik** [comment]
looks good now:

https://ci.sparrowhub.io/report/2092

```
04:36:18 :: O----------------O--------O---------------------------------------------------------O------------O
04:36:18 :: | Rakudo Version | Status | Time                                                    | Linux Dist |
04:36:18 :: O================O========O=========================================================O============O
04:36:18 :: | 2022.07        | OK     | 0:51.47 real,54.48 user,1.55 sys | CPU Percentage: 108% | debian     |
04:36:18 :: | 2022.12        | OK     | 0:59.69 real,63.64 user,1.87 sys | CPU Percentage: 109% | debian     |
04:36:18 :: --------------------------------------------------------------------------------------------------
```
